//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.Properties.F1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebServices.Properties.F1.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.0336079,50.5081322.
        /// </summary>
        internal static string BAHRAIN_INTERNATIONAL_CIRCUIT {
            get {
                return ResourceManager.GetString("BAHRAIN_INTERNATIONAL_CIRCUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.0336079,50.5081322.
        /// </summary>
        internal static string BAHRAIN_INTERNATIONAL_CIRCUIT___OUTER_TRACK {
            get {
                return ResourceManager.GetString("BAHRAIN_INTERNATIONAL_CIRCUIT_-_OUTER_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.957914,29.4116749.
        /// </summary>
        internal static string INTERCITY_ISTANBUL_PARK {
            get {
                return ResourceManager.GetString("INTERCITY_ISTANBUL_PARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.4698914,54.603292.
        /// </summary>
        internal static string YAS_MARINA_CIRCUIT {
            get {
                return ResourceManager.GetString("YAS_MARINA_CIRCUIT", resourceCulture);
            }
        }
    }
}
